[build]
  publish = "dist"
  command = "npm ci && npm install @rollup/rollup-linux-x64-gnu@4.13.0 && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps" 